### ISSUE TITLE
error read next packet when packet data is too large. #1

### ISSUE THREAD

**Issue by mfdl** [lakatop/USB_Packet_Analyzer#1]
FileReader::GetPacket() when packet data is too large ret bytes != data Len + header Len. if skip check it works . buf fail to read next packet.

**Comment by lakatop** [comment]
Size of maximal packet data is limited by [USBPcap structure](https://desowin.org/usbpcap/captureformat.html) itself - `dataLength` field is defined as `UINT32` (=4B = ~4 billions), so you probably won't be able to analyze bigger packets than that.

**Comment by MofadalAltyeb** [comment]
Hello thanks,
proplem solved by using this.
qint32 TestHugeURBBuff()
{
    QString path = qApp->applicationDirPath() + "mofadal/mtk-research/mt6768/MTK_SEC.pcap";
    QByteArray buff = MRXCrypto::ReadFile(path);
    QBuffer iodev(&buff);
    if (!iodev.open(QBuffer::ReadOnly))
        throwException(iodev.errorString());
    
    // read pcap header in the beginning of the file and some sanity checking
    pcap_hdr_s head = {};
    qint64 bread = iodev.read((char*)&head, sizeof(pcap_hdr_s));
    if (bread != sizeof(pcap_hdr_s))
    {
        qInfo().noquote() << "cant read pcap_hdr_s from input file";;
        return 0;
    }
    
    qint64 snaplen = head.snaplen;
    qint16 index = 0;
    
    while (!iodev.atEnd())
    {
        // read per record header and some sanity checking.
        pcaprec_hdr_s record = {};
        bread = iodev.read((char*)&record, sizeof(pcaprec_hdr_s));
        if (bread != sizeof(pcaprec_hdr_s)) {
            qInfo().noquote() << "cant read pcaprec_hdr_s from input file";
            return 0;
        }
        qint64 pkt_len = record.incl_len;
        qInfo().nospace()  << "pckt len: " << pkt_len;
        if (pkt_len > snaplen) {
            qInfo().noquote() << QString("error in pcap file. incl_len(%0) > snaplen(%1)").arg(pkt_len, snaplen);
            return 0;
        }
        
        // read pckt from pcap file
        QByteArray pkt(pkt_len, Qt::Uninitialized);
        bread = iodev.read(pkt.data(), pkt.size());
        if (bread != pkt_len) {
            qInfo().noquote() << "cant read packet from pcap file";
            return 0;
        }
        
        //read usbpcap packet header data
        const unsigned char* packet = (unsigned char*)pkt.data();
        PUSBPCAP_BUFFER_PACKET_HEADER usbh = (PUSBPCAP_BUFFER_PACKET_HEADER)packet;
        packet += usbh->headerLen;// sizeof(PUSBPCAP_BUFFER_PACKET_HEADER);
        
        if(!usbh->dataLength)
            continue;
        
        QString type = (usbh->endpoint & 0x80) ? "IN" : "OUT";
        
        qInfo().noquote() << "pktlen!" <<pkt.size() << "dataLen"  << usbh->dataLength;
        
        if(usbh->dataLength > pkt.size())
            usbh->dataLength = pkt.size() - sizeof (USBPCAP_BUFFER_PACKET_HEADER);
        
        QByteArray urbPkt = QByteArray::fromRawData((char*)packet, usbh->dataLength);
        
        if(usbh->transfer == USBPCAP_TRANSFER_BULK)
        {
            index++;
            
            qInfo().noquote() << "(usbh->transfer == USBPCAP_TRANSFER_BULK)";
            
            QString endpoint = (usbh->endpoint & 0x80) ? "IN" : "OUT";
            if(urbPkt.size())
            {
                qInfo().noquote() << "USBPCAP_TRANSFER_BULK::" << index << endpoint << pkt.size() << bread ;
                
                if(urbPkt.size() < 0xa*3)
                {
                    //qInfo().noquote() << "USBPCAP_TRANSFER_BULK::" << endpoint << urb.toHex() << pkt.size() << bread << maxLen;
                    send_ui_log(endpoint + "_" + urbPkt.toHex().data());
                }
            }
        }
    }
}
